#pragma once
#include "Message.h"

char msgIDtoStr_toServer[7][64] = { 
  "MSG_NOINFO" ,  
  "MSG_REQ_SCOREBOARD",
  "MSG_LOBBY_ENTER",
  "MSG_LOBBY_READY",
  "MSG_LOBBY_START",
  "MSG_LOBBY_CHAT_TOSERVER",
  "MSG_BALLDATA_TOSERVER"
};

char msgIDtoStr_toClient[13][64] = {
  "MSG_NOINFO",
  "MSG_LOBBY_STATUS",
  "MSG_LOBBY_CHAT_TOCLIENT",
  "MSG_PLAYDATA_TOCLIENT",
  "MSG_PLAY_START",
  "MSG_PLAY_END",
  "MSG_PLAY_KILLLOG",
  "MSG_PLAY_SCOREBOARD",
  "MSG_PLAY_TIME",
  "MSG_PLAY_ITEM",
  "MSG_SCOREBOARD",
  "MSG_SET_INDEX",
  "MSG_ERR_GAME_ONPROGRESS"
};
